# Generated by Django 5.2.13 on 2026-04-17 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_item_reorder_point_item_reorder_quantity_item_sku_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, help_text='Product image', null=True, upload_to='items/'),
        ),
    ]
